#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 22 14:44:14 2025

@author: nicolasfihey
"""
import numpy as np
import matplotlib.pyplot as plt


L=2
l=1
N=100
GZ=[]

"""rectangle posé sur l'eau"""

alpha = np.linspace(0, 90, N) #On s'arrête à 90° car après on change de point d'appui
for i in range(N):
    GZ.append(np.cos(alpha[i]*np.pi/180)*L/2 - np.sin(alpha[i]*np.pi/180)*l/2)

plt.plot(alpha,GZ)
plt.title("GZ rectangle sur l'eau")
plt.xlabel('alpha (en °)')                    
plt.ylabel('GZ (en m)') 
plt.grid(True)


"""rectangle dans cercle posé sur l'eau"""
