[project]
name = "hydrostatic"
version = "0.1.0"
description = "Hydrostatic computation"
readme = "README.md"
requires-python = ">=3.10,<3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy==1.23.5",
    "scipy>=1.14.0",
]

[dependency-groups]
dev = [
    "coverage>=7.6.10",
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
    "ruff>=0.9.3",
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
